# Site settings
title: Cambodia Offroad Adventures
subtitle: 2024
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up,<br>
  ported to Jekyll by MOODULE<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
facebook_url: https://www.facebook.com/leng.i.leng
#instagram_url: https://github.com/moodule
#pinterest_url: https://github.com/moodule
#twitter_url: https://github.com/moodule

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6LdzdcgUAAAAAF-3fFepKyWHRf0Yg1PHegY8z-pl

# Collections
collections:
  parallelism:
    output: false
    date: 2024-01-07
  shiva:
    output: false
    date: 2024-01-08

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing
